// Watchlists for the live (Yahoo) Investments feed. NSE tickers carry the `.NS`
// suffix; metals use CME futures symbols. Indian stocks are split by intent:
// growth, dividend (income), and penny (low-price, speculative). Any ticker Yahoo
// can't resolve is silently dropped, so the lists can be generous.

export type StockDef = { symbol: string; name: string; sector: string };
export type MetalDef = { symbol: string; name: string };

export const GROWTH_STOCKS: StockDef[] = [
  { symbol: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy / Conglomerate" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services", sector: "IT Services" },
  { symbol: "INFY.NS", name: "Infosys", sector: "IT Services" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies", sector: "IT Services" },
  { symbol: "WIPRO.NS", name: "Wipro", sector: "IT Services" },
  { symbol: "TECHM.NS", name: "Tech Mahindra", sector: "IT Services" },
  { symbol: "LTIM.NS", name: "LTIMindtree", sector: "IT Services" },
  { symbol: "PERSISTENT.NS", name: "Persistent Systems", sector: "IT Services" },
  { symbol: "COFORGE.NS", name: "Coforge", sector: "IT Services" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank", sector: "Banking" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank", sector: "Banking" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", sector: "Banking" },
  { symbol: "AXISBANK.NS", name: "Axis Bank", sector: "Banking" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance", sector: "NBFC" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv", sector: "Financials" },
  { symbol: "JIOFIN.NS", name: "Jio Financial", sector: "Financials" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors", sector: "Auto" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra", sector: "Auto" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki", sector: "Auto" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors", sector: "Auto" },
  { symbol: "TVSMOTOR.NS", name: "TVS Motor", sector: "Auto" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto", sector: "Auto" },
  { symbol: "TRENT.NS", name: "Trent", sector: "Retail" },
  { symbol: "DMART.NS", name: "Avenue Supermarts", sector: "Retail" },
  { symbol: "TITAN.NS", name: "Titan Company", sector: "Consumer" },
  { symbol: "ETERNAL.NS", name: "Eternal (Zomato)", sector: "Internet" },
  { symbol: "DIXON.NS", name: "Dixon Technologies", sector: "Electronics Mfg" },
  { symbol: "POLYCAB.NS", name: "Polycab India", sector: "Cap Goods" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Telecom" },
  { symbol: "LT.NS", name: "Larsen & Toubro", sector: "Infrastructure" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises", sector: "Conglomerate" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports", sector: "Infrastructure" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints", sector: "Consumer" },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries", sector: "Chemicals" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharma", sector: "Pharma" },
  { symbol: "DRREDDY.NS", name: "Dr Reddy's Labs", sector: "Pharma" },
  { symbol: "CIPLA.NS", name: "Cipla", sector: "Pharma" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories", sector: "Pharma" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals", sector: "Healthcare" },
  { symbol: "INDIGO.NS", name: "InterGlobe (IndiGo)", sector: "Aviation" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics", sector: "Defence" },
  { symbol: "BEL.NS", name: "Bharat Electronics", sector: "Defence" },
  { symbol: "SIEMENS.NS", name: "Siemens India", sector: "Cap Goods" },
  { symbol: "DLF.NS", name: "DLF", sector: "Realty" },
];

export const DIVIDEND_STOCKS: StockDef[] = [
  { symbol: "ITC.NS", name: "ITC", sector: "FMCG" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "FMCG" },
  { symbol: "NESTLEIND.NS", name: "Nestle India", sector: "FMCG" },
  { symbol: "COALINDIA.NS", name: "Coal India", sector: "Mining" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corp", sector: "Utilities" },
  { symbol: "NTPC.NS", name: "NTPC", sector: "Utilities" },
  { symbol: "ONGC.NS", name: "Oil & Natural Gas", sector: "Energy" },
  { symbol: "IOC.NS", name: "Indian Oil", sector: "Energy" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum", sector: "Energy" },
  { symbol: "HINDPETRO.NS", name: "Hindustan Petroleum", sector: "Energy" },
  { symbol: "GAIL.NS", name: "GAIL India", sector: "Energy" },
  { symbol: "OIL.NS", name: "Oil India", sector: "Energy" },
  { symbol: "HINDZINC.NS", name: "Hindustan Zinc", sector: "Metals" },
  { symbol: "VEDL.NS", name: "Vedanta", sector: "Metals / Mining" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel", sector: "Metals" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel", sector: "Metals" },
  { symbol: "SAIL.NS", name: "SAIL", sector: "Metals" },
  { symbol: "NMDC.NS", name: "NMDC", sector: "Mining" },
  { symbol: "REC.NS", name: "REC Ltd", sector: "Financials" },
  { symbol: "PFC.NS", name: "Power Finance Corp", sector: "Financials" },
  { symbol: "IRFC.NS", name: "Indian Railway Finance", sector: "Financials" },
  { symbol: "SBIN.NS", name: "State Bank of India", sector: "Banking" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement", sector: "Cement" },
  { symbol: "GRASIM.NS", name: "Grasim Industries", sector: "Diversified" },
  { symbol: "CASTROLIND.NS", name: "Castrol India", sector: "Lubricants" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda", sector: "Banking" },
  { symbol: "CANBK.NS", name: "Canara Bank", sector: "Banking" },
  { symbol: "NHPC.NS", name: "NHPC", sector: "Utilities" },
  { symbol: "SJVN.NS", name: "SJVN", sector: "Utilities" },
];

export const PENNY_STOCKS: StockDef[] = [
  { symbol: "SUZLON.NS", name: "Suzlon Energy", sector: "Renewables" },
  { symbol: "YESBANK.NS", name: "Yes Bank", sector: "Banking" },
  { symbol: "IDEA.NS", name: "Vodafone Idea", sector: "Telecom" },
  { symbol: "RPOWER.NS", name: "Reliance Power", sector: "Power" },
  { symbol: "JPPOWER.NS", name: "Jaiprakash Power", sector: "Power" },
  { symbol: "TRIDENT.NS", name: "Trident", sector: "Textiles" },
  { symbol: "SOUTHBANK.NS", name: "South Indian Bank", sector: "Banking" },
  { symbol: "IOB.NS", name: "Indian Overseas Bank", sector: "Banking" },
  { symbol: "UCOBANK.NS", name: "UCO Bank", sector: "Banking" },
  { symbol: "CENTRALBK.NS", name: "Central Bank of India", sector: "Banking" },
  { symbol: "MAHABANK.NS", name: "Bank of Maharashtra", sector: "Banking" },
  { symbol: "PNB.NS", name: "Punjab National Bank", sector: "Banking" },
  { symbol: "MTNL.NS", name: "MTNL", sector: "Telecom" },
  { symbol: "GTLINFRA.NS", name: "GTL Infrastructure", sector: "Telecom Infra" },
  { symbol: "NBCC.NS", name: "NBCC India", sector: "Construction" },
  { symbol: "IFCI.NS", name: "IFCI", sector: "Financials" },
  { symbol: "HUDCO.NS", name: "HUDCO", sector: "Financials" },
  { symbol: "RTNPOWER.NS", name: "RattanIndia Power", sector: "Power" },
  { symbol: "JPASSOCIAT.NS", name: "Jaiprakash Associates", sector: "Infra" },
  { symbol: "ALOKINDS.NS", name: "Alok Industries", sector: "Textiles" },
  { symbol: "IRB.NS", name: "IRB Infrastructure", sector: "Infra" },
  { symbol: "RVNL.NS", name: "Rail Vikas Nigam", sector: "Infra" },
  { symbol: "IREDA.NS", name: "IREDA", sector: "Financials" },
  { symbol: "BHEL.NS", name: "BHEL", sector: "Cap Goods" },
  { symbol: "TATAPOWER.NS", name: "Tata Power", sector: "Power" },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank", sector: "Banking" },
  { symbol: "ZEEL.NS", name: "Zee Entertainment", sector: "Media" },
  { symbol: "RTNINDIA.NS", name: "RattanIndia Enterprises", sector: "Diversified" },
];

export const METALS: MetalDef[] = [
  { symbol: "GC=F", name: "Gold" },
  { symbol: "SI=F", name: "Silver" },
  { symbol: "PL=F", name: "Platinum" },
  { symbol: "PA=F", name: "Palladium" },
  { symbol: "HG=F", name: "Copper" },
];

// US large-caps (USD, no suffix). Yahoo resolves these directly.
export const US_STOCKS: StockDef[] = [
  { symbol: "AAPL", name: "Apple", sector: "Technology" },
  { symbol: "MSFT", name: "Microsoft", sector: "Technology" },
  { symbol: "NVDA", name: "NVIDIA", sector: "Semiconductors" },
  { symbol: "GOOGL", name: "Alphabet", sector: "Internet" },
  { symbol: "AMZN", name: "Amazon", sector: "E-commerce" },
  { symbol: "META", name: "Meta Platforms", sector: "Internet" },
  { symbol: "TSLA", name: "Tesla", sector: "Auto / EV" },
  { symbol: "AVGO", name: "Broadcom", sector: "Semiconductors" },
  { symbol: "JPM", name: "JPMorgan Chase", sector: "Banking" },
  { symbol: "V", name: "Visa", sector: "Financials" },
  { symbol: "MA", name: "Mastercard", sector: "Financials" },
  { symbol: "UNH", name: "UnitedHealth", sector: "Healthcare" },
  { symbol: "XOM", name: "Exxon Mobil", sector: "Energy" },
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Pharma" },
  { symbol: "WMT", name: "Walmart", sector: "Retail" },
  { symbol: "PG", name: "Procter & Gamble", sector: "Consumer" },
  { symbol: "COST", name: "Costco", sector: "Retail" },
  { symbol: "NFLX", name: "Netflix", sector: "Media" },
  { symbol: "AMD", name: "AMD", sector: "Semiconductors" },
  { symbol: "CRM", name: "Salesforce", sector: "Software" },
  { symbol: "ORCL", name: "Oracle", sector: "Software" },
  { symbol: "ADBE", name: "Adobe", sector: "Software" },
  { symbol: "KO", name: "Coca-Cola", sector: "Consumer" },
  { symbol: "DIS", name: "Walt Disney", sector: "Media" },
];

// ETFs (USD). Broad index, sector and commodity funds.
export const ETFS: StockDef[] = [
  { symbol: "SPY", name: "SPDR S&P 500", sector: "US Large Cap" },
  { symbol: "QQQ", name: "Invesco QQQ (Nasdaq 100)", sector: "US Tech" },
  { symbol: "VOO", name: "Vanguard S&P 500", sector: "US Large Cap" },
  { symbol: "VTI", name: "Vanguard Total Market", sector: "US Broad" },
  { symbol: "IWM", name: "iShares Russell 2000", sector: "US Small Cap" },
  { symbol: "DIA", name: "SPDR Dow Jones", sector: "US Large Cap" },
  { symbol: "ARKK", name: "ARK Innovation", sector: "Disruptive Growth" },
  { symbol: "XLK", name: "Technology Select SPDR", sector: "US Tech" },
  { symbol: "XLF", name: "Financials Select SPDR", sector: "US Financials" },
  { symbol: "XLE", name: "Energy Select SPDR", sector: "US Energy" },
  { symbol: "GLD", name: "SPDR Gold Shares", sector: "Commodity · Gold" },
  { symbol: "SLV", name: "iShares Silver Trust", sector: "Commodity · Silver" },
  { symbol: "VEA", name: "Vanguard Developed Mkts", sector: "Intl Developed" },
  { symbol: "VWO", name: "Vanguard Emerging Mkts", sector: "Emerging Mkts" },
  { symbol: "SCHD", name: "Schwab US Dividend", sector: "US Dividend" },
];

// Mutual funds (USD NAV). Yahoo serves daily NAV for these tickers.
export const MUTUAL_FUNDS: StockDef[] = [
  { symbol: "VFIAX", name: "Vanguard 500 Index Admiral", sector: "US Large Blend" },
  { symbol: "FXAIX", name: "Fidelity 500 Index", sector: "US Large Blend" },
  { symbol: "VTSAX", name: "Vanguard Total Stock Mkt", sector: "US Broad" },
  { symbol: "SWPPX", name: "Schwab S&P 500 Index", sector: "US Large Blend" },
  { symbol: "FCNTX", name: "Fidelity Contrafund", sector: "US Large Growth" },
  { symbol: "VWELX", name: "Vanguard Wellington", sector: "Balanced" },
  { symbol: "AGTHX", name: "American Funds Growth", sector: "US Large Growth" },
  { symbol: "FBGRX", name: "Fidelity Blue Chip Growth", sector: "US Large Growth" },
  { symbol: "PRGFX", name: "T. Rowe Price Growth", sector: "US Large Growth" },
  { symbol: "VBTLX", name: "Vanguard Total Bond", sector: "Fixed Income" },
];

// Headline indices for the Market Overview ribbon. INR for Indian indices.
export const INDICES: { symbol: string; name: string; currency: string }[] = [
  { symbol: "^NSEI", name: "Nifty 50", currency: "INR" },
  { symbol: "^BSESN", name: "Sensex", currency: "INR" },
  { symbol: "^NSEBANK", name: "Bank Nifty", currency: "INR" },
  { symbol: "^GSPC", name: "S&P 500", currency: "USD" },
  { symbol: "^IXIC", name: "Nasdaq", currency: "USD" },
  { symbol: "^DJI", name: "Dow Jones", currency: "USD" },
];

export const ALL_STOCKS = [...GROWTH_STOCKS, ...DIVIDEND_STOCKS, ...PENNY_STOCKS];
