// Agent Factory — the meta-agent ("robot that builds robots").
// Given a spec, it produces the artifacts a NEW self-improving agent needs:
//   1. a daily improver TARGET (joins scripts/self-improve.config.json) so the
//      new agent starts evolving its own domain every cycle, and
//   2. a registry entry + executor stub to register it on the platform.
// Pure functions only (no fs / no server-only) so both the website (preview)
// and the runner (apply) can use them. Applying happens through the normal
// PR-gated flow — never a silent server write.

export type AgentSpec = {
  /** kebab id, e.g. "spanish-tutor" */
  id: string;
  name: string;
  icon: string;
  category: string;
  /** human domain, e.g. "Spanish language learning" */
  domain: string;
  /** globs the improver reads + writes each cycle */
  globs: string[];
  /** what to build/improve every cycle */
  instruction: string;
  capabilities?: string[];
};

export type ImproverTarget = {
  agent: string;
  title: string;
  globs: string[];
  instruction: string;
};

const kebab = (s: string) => s.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

/** The daily self-improve target that makes this agent autonomous. */
export function buildImproverTarget(spec: AgentSpec): ImproverTarget {
  return {
    agent: kebab(spec.id),
    title: `${spec.name} — daily improvement`,
    globs: spec.globs,
    instruction: spec.instruction,
  };
}

/** Append a target to the existing config text, returning the new file content. */
export function addTargetToConfig(configText: string, target: ImproverTarget): string {
  const cfg = JSON.parse(configText) as { targets: ImproverTarget[] } & Record<string, unknown>;
  if (cfg.targets.some((t) => t.agent === target.agent)) {
    cfg.targets = cfg.targets.map((t) => (t.agent === target.agent ? target : t));
  } else {
    cfg.targets.push(target);
  }
  return JSON.stringify(cfg, null, 2) + "\n";
}

/** Registry entry source the platform can drop into AGENT_REGISTRY. */
export function agentRegistrySnippet(spec: AgentSpec): string {
  const caps = (spec.capabilities ?? ["self-improve", "code-generation"]).map((c) => `"${c}"`).join(", ");
  return `  {
    id: ${JSON.stringify(kebab(spec.id))},
    name: ${JSON.stringify(spec.name)},
    icon: ${JSON.stringify(spec.icon)},
    description: ${JSON.stringify(`Self-improving agent — ${spec.domain}. Builds + improves its domain every cycle (free open-source models, PR-gated).`)},
    category: ${JSON.stringify(spec.category)},
    capabilities: [${caps}],
    tools: ["filesystem", "knowledge"],
    visibility: "public",
    version: "1.0.0",
    health: "healthy",
    status: "idle",
    enabled: true,
    lastActivityAt: null,
  },`;
}

/** A minimal executor stub so the new agent is `isExecutable` on the platform. */
export function executorStub(spec: AgentSpec): { path: string; content: string } {
  const id = kebab(spec.id);
  const fn = id.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + "Executor";
  return {
    path: `lib/agents/generated/${id}.ts`,
    content: `import type { AgentExecutor } from "../executor";

// Auto-generated by the Agent Factory. The agent's real evolution work runs in
// the daily self-improve loop (scripts/self-improve.mjs, target "${id}"). This
// executor lets the platform invoke a one-off plan preview on demand.
export const ${fn}: AgentExecutor = {
  agentId: ${JSON.stringify(id)},
  async execute(ctx) {
    return {
      ok: true,
      summary: ${JSON.stringify(`${spec.name} queued — domain: ${spec.domain}. Improvements ship as PRs via the self-improve loop.`)},
      output: { goal: ctx.input.goal, domain: ${JSON.stringify(spec.domain)} },
    };
  },
};
`,
  };
}

/** Full scaffold: everything needed to birth a new self-improving agent. */
export function scaffoldAgent(spec: AgentSpec, currentConfigText: string) {
  const target = buildImproverTarget(spec);
  return {
    summary: `Scaffolded self-improving agent "${spec.name}" (${kebab(spec.id)}) for ${spec.domain}.`,
    target,
    files: [
      { path: "scripts/self-improve.config.json", action: "edit" as const, content: addTargetToConfig(currentConfigText, target) },
      { ...executorStub(spec), action: "create" as const },
    ],
    registrySnippet: agentRegistrySnippet(spec),
  };
}
